In [2]:
import numpy as np
import cv2
import time

# distance from camera to object(face) measured
KNOW_DISTANCE = 500

# width of face in the real world or Object Plane
KNOWN_WIDTH = 400

## colors
Green = (0,255,0)          
Red = (0,0,255)
Black = (255,255,255)
White = (0,0,0)

## define fonts
fonts = cv2.FONT_HERSHEY_COMPLEX

## car detector
car_detector = cv2.CascadeClassifier('haarcascade_car.xml')


## focal length finder
def Focal_length_finder(measured_distance, real_width, width_in_rf_image):

    focal_length = (width_in_rf_image * measured_distance) / real_width

    return focal_length

## distance estimator fuction
def Distance_finder(Focal_length, real_car_width, car_width_in_frame):

    distace = (real_car_width * Focal_length) / car_width_in_frame

    return distace


def face_data(image):

    car_width = 0

    ## converting color image to gray scale image
    gray_image = cv2.cvtColor(image ,cv2.COLOR_BGR2GRAY)

    ## detecting face in the image
    cars = car_detector.detectMultiScale(gray_image, 1.3, 5)
    
#     print(cars)
#     print(len(cars))

    ## looping through the car detect in the image
    ## getting coordinates  x, y, width & height

    for (x,y,h,w) in cars:

        ## draw rectangle on the car
        cv2.rectangle(image, (x,y), (x+w , y+h), Green, 2)

        ## getting car width in the pixels
        car_width = w
    
    return car_width

## reading reference image from directory
ref_image = cv2.imread('car.jpg')

## find the car width(pixels) in the reference_image
ref_image_car_width = car_data(ref_image)

## get the focal by calling "focal_length_finder"
## car width in reference(pixels)
## known distance in (centimeter)
## known width in (centimeter)
Focal_length_found = Focal_length_finder(KNOW_DISTANCE, KNOWN_WIDTH, ref_image_car_width)

print(Focal_length_found)

## show the reference image 
cv2.imshow('window', ref_image)

## initialize the camera object so taht we can get frame from it
cap = cv2.VideoCapture('car1.mp4')

## looping through frame, incoming from camera / or / video
while cap.isOpened():
    
    time.sleep(0.05)

    ## reading the frame from camera
    _, frame  = cap.read()

    ## calling face_data fuction to find the width of the car(pixels) in the frame
    car_width_in_frame = car_data(frame)

    ## check if the car is zero then don't find the distance ... otherwise run the if loop 
    if car_width_in_frame != 0:

        # finding the distance by calling function 
        # Distance finder function need 
        # these arguments the Focal_Length,
        # Known_width(centimeters),
        # and Known_distance(centimeters)
        Distance = Distance_finder(Focal_length_found, KNOWN_WIDTH, car_width_in_frame)

        # print(Distance)
        
        ## draw line as background of text
        cv2.line(frame, (30,30), (230,30), Red, 32)
        cv2.line(frame, (30,30), (230,30), Black, 28)

        ## Put text on the line
        cv2.putText(frame, f"Distance : {round(Distance ,2)} CM", (30,35), fonts, 0.6, Green, 2)

    ## show the frame on the screen
    cv2.imshow('window', frame)

    ## quit the program by pressing  "Q" button
    if cv2.waitKey(1) == ord("q"):
        break

## closing the camera
cap.release()

## closing the windows that are opened
cv2.destroyAllWindows()

[[2776 1244   44   44]
 [1833  759   44   44]]
2
55.0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
[[969 447  82  82]]
1
[[969 447  82  82]]
1
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
[[966 437  76  76]]
1
[[966 437  76  76]]
1
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
[[966 477  90  90]]
1
[[966 475  91  91]]
1
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0
()
0